import { dedent } from 'ts-dedent';
import { describe, expect, it } from 'vitest';

import { createEsModulesComponentsFile } from './create-es-modules-components-file.js';

describe('createComponentWrappers', () => {
  it('should generate a react component wrapper', async () => {
    const code = await createEsModulesComponentsFile({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        },
        {
          tagName: 'my-other-component',
          componentClassName: 'MyOtherComponent',
          events: [],
        } as any,
      ],
    });

    expect(code).toEqual(dedent`/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */
export { MyComponent } from './my-component.js';
export { MyOtherComponent } from './my-other-component.js';

`);
  });

  it('should generate a server barrel with the default serializeShadowRoot when componentSuffix is set', async () => {
    const code = await createEsModulesComponentsFile({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          events: [],
        },
        {
          tagName: 'my-other-component',
          componentClassName: 'MyOtherComponent',
          events: [],
        },
      ] as any,
      filename: 'components.server.ts',
      componentSuffix: '.server',
    });

    expect(code).toEqual(dedent`/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */
import type { SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };
export { MyComponent } from './my-component.server.js';
export { MyOtherComponent } from './my-other-component.server.js';

`);
  });

  it('should JSON-stringify a custom serializeShadowRoot in the server barrel', async () => {
    const code = await createEsModulesComponentsFile({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          events: [],
        },
      ] as any,
      filename: 'components.server.ts',
      componentSuffix: '.server',
      serializeShadowRoot: { 'declarative-shadow-dom': ['my-component'], default: 'scoped' },
    });

    expect(code).toEqual(dedent`/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */
import type { SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
export const serializeShadowRoot: SerializeShadowRootOptions = {"declarative-shadow-dom":["my-component"],"default":"scoped"};
export { MyComponent } from './my-component.server.js';

`);
  });
});
