import { describe, it, expect, afterEach } from 'vitest';
import { dedent } from 'ts-dedent';

import { createComponentWrappers } from './create-component-wrappers.js';

describe('createComponentWrappers', () => {
  const files = new Map<string, string>();
  const writeFile = (path: string, contents: string) => {
    files.set(path, contents);
    return Promise.resolve();
  };

  afterEach(() => {
    files.clear();
  });

  it('should generate a react component wrapper', async () => {
    await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          properties: [],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      writeFile,
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
    });

    expect(files.get('dist/my-output-path/components.ts')).toEqual(dedent`'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import React from 'react';
import { createComponent } from '@stencil/react-output-target/runtime';
import type { Components } from 'my-package/dist/custom-elements';
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from 'my-package/dist/custom-elements/my-component.js';
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent,
});

`);
  });

  it('should generate a react component wrapper with ES modules', async () => {
    await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          properties: [],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: true,
      writeFile,
    });

    expect(files.get('dist/my-output-path/components.ts')).toEqual(dedent`/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */
export { MyComponent } from './my-component.js';

`);

    expect(files.get('dist/my-output-path/my-component.ts')).toEqual(dedent`'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import React from 'react';
import { createComponent } from '@stencil/react-output-target/runtime';
import type { Components } from 'my-package/dist/custom-elements';
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from 'my-package/dist/custom-elements/my-component.js';
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent,
});

`);
  });

  it('should not generate component wrappers for internal components', async () => {
    await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          properties: [],
          internal: true,
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      writeFile,
    });

    expect(files.size).toEqual(0);
  });

  it('should filter out excludedComponents', async () => {
    await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      excludeComponents: ['my-component'],
      writeFile,
    });

    expect(files.size).toEqual(0);
  });

  it('should generate event types from references', async () => {
    await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          properties: [],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              internal: false,
              complexType: {
                original: 'IButton',
                resolved: '{ element: HTMLMyComponentElement; context: MyComponent; event: Event; }',
                references: {
                  IButton: {
                    location: 'import',
                    path: '../../types/my-component',
                    id: 'src/types/my-component.d.ts::IMyComponent',
                  },
                },
              },
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      writeFile,
    });

    expect(files.get('dist/my-output-path/components.ts')).toEqual(dedent`'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import React from 'react';
import { createComponent } from '@stencil/react-output-target/runtime';
import type { Components } from 'my-package/dist/custom-elements';
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from 'my-package/dist/custom-elements/my-component.js';
import type { IButton, MyComponentCustomEvent } from 'my-package';
import type { StencilReactComponent, EventName } from '@stencil/react-output-target/runtime';

export type MyComponentEvents = {
  onMyEvent: EventName<MyComponentCustomEvent<IButton>>
};

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
      onMyEvent: 'myEvent'
    } as MyComponentEvents,
    defineCustomElement: defineMyComponent,
});

    `);
  });

  it('creates next.js component wrappers', async () => {
    await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          properties: [
            {
              name: 'hasMaxLength',
              attribute: 'max-length',
            },
            {
              name: 'links',
            },
          ],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      hydrateModule: 'my-package/hydrate',
      writeFile,
    });

    expect(files.size).toBe(2);

    expect(files.get('dist/my-output-path/components.server.ts'))
      .toContain(`export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    properties: {
      hasMaxLength: 'max-length'
    },
    hydrateModule: typeof window === 'undefined' ? (import('my-package/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyComponent as StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>,
    serializeShadowRoot,
});
`);
  });

  it('can exclude components for server side rendering', async () => {
    await createComponentWrappers({
      components: [
        {
          tagName: 'my-component-a',
          componentClassName: 'MyComponentA',
          properties: [
            {
              name: 'hasMaxLength',
              attribute: 'max-length',
            },
            {
              name: 'links',
            },
          ],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
        {
          tagName: 'my-component-b',
          componentClassName: 'MyComponentB',
          properties: [
            {
              name: 'hasMaxLength',
              attribute: 'max-length',
            },
            {
              name: 'links',
            },
          ],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      hydrateModule: 'my-package/hydrate',
      excludeServerSideRenderingFor: ['my-component-a'],
      writeFile,
    });

    const code = files.get('dist/my-output-path/components.server.ts');
    expect(code).not.toContain('createComponent<MyComponentAElement, MyComponentAEvents, Components.MyComponentA>({');
    expect(code).toContain('createComponent<MyComponentBElement, MyComponentBEvents, Components.MyComponentB>({');
  });

  it('should generate a server barrel when esModules: true and hydrateModule are both set', async () => {
    await createComponentWrappers({
      components: [
        {
          tagName: 'my-component-a',
          componentClassName: 'MyComponentA',
          properties: [],
          events: [],
        } as any,
        {
          tagName: 'my-component-b',
          componentClassName: 'MyComponentB',
          properties: [],
          events: [],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: true,
      hydrateModule: 'my-package/hydrate',
      excludeServerSideRenderingFor: ['my-component-a'],
      writeFile,
    });

    /**
     * Find the generated barrels and per-component server files by file path
     * since the order of `sourceFiles` mixes the in-memory ts-morph results
     * (barrels) with the on-disk `createComponentFile` outputs.
     */

    const clientBarrel = Array.from(files.keys()).find((p) => p.endsWith('/components.ts'));
    const serverBarrel = Array.from(files.keys()).find((p) => p.endsWith('/components.server.ts'));
    const serverPerComponentA = Array.from(files.keys()).find((p) => p.endsWith('/my-component-a.server.ts'));
    const serverPerComponentB = Array.from(files.keys()).find((p) => p.endsWith('/my-component-b.server.ts'));

    expect(clientBarrel).toBeDefined();
    expect(serverBarrel).toBeDefined();

    /**
     * Per-component server file for the non-excluded component is still produced.
     * The excluded component's per-component server file ends up empty (filtered
     * to zero exports) — which matches the existing `createComponentFile` behavior
     * — so we don't assert on its absence here, only that the included one exists.
     */
    expect(serverPerComponentB).toBeDefined();

    const serverBarrelText = files.get(serverBarrel);
    expect(serverBarrelText).toContain(
      `import type { SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';`
    );
    expect(serverBarrelText).toContain(
      'export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };'
    );
    expect(serverBarrelText).toContain(`export { MyComponentB } from './my-component-b.server.js';`);
    expect(serverBarrelText).not.toContain('my-component-a.server.js');
    expect(serverBarrelText).not.toContain('MyComponentA');

    // Sanity check: the excluded per-component path is not silently used.
    expect(serverPerComponentA).toBeDefined(); // still emitted, but with no exports
  });
});
