import type { ComponentCompilerMeta } from '@stencil/core/internal';
import { eventListenerName, kebabToPascalCase, normalizeTypeString } from './utils/string-utils.js';
import type { RenderToStringOptions } from './runtime/ssr.js';

interface ReactEvent {
  originalName: string;
  name: string;
  type: string;
}

const autogeneratedComment = `/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */`;

export const createStencilReactComponents = ({
  components,
  stencilPackageName,
  customElementsDir,
  componentsTypesDir,
  hydrateModule,
  clientModule,
  serializeShadowRoot,
  transformTag,
}: {
  components: ComponentCompilerMeta[];
  stencilPackageName: string;
  customElementsDir: string;
  componentsTypesDir: string;
  hydrateModule?: string;
  clientModule?: string;
  serializeShadowRoot?: RenderToStringOptions['serializeShadowRoot'];
  transformTag?: boolean;
}) => {
  const isSSRModule = hydrateModule && clientModule;

  const imports: (string | false | undefined)[] = [
    !isSSRModule && `import React from 'react';`,
    ...(hydrateModule
      ? [
          transformTag && `import { getTagTransformer } from './tag-transformer.js';`,
          `import { createComponent, type SerializeShadowRootOptions, type HydrateModule } from '@stencil/react-output-target/ssr';`,
        ]
      : [
          transformTag && `import { transformTag } from './tag-transformer.js';`,
          `import { createComponent } from '@stencil/react-output-target/runtime';`,
        ]),
    `import type { Components } from '${stencilPackageName}/${componentsTypesDir}';`,
  ];

  const exports: (string | false)[] = [];

  /**
   * Add imports for react client components if hydrateModule is provided.
   * This import needs a @ts-ignore comment.
   */
  if (isSSRModule) {
    const namedImports = components
      .map(({ tagName }) => {
        const reactTagName = kebabToPascalCase(tagName);
        return `${reactTagName} as ${reactTagName}React`;
      })
      .join(', ');
    imports.push(
      '// @ts-ignore - ignore potential type issues as the project is importing itself',
      `import { ${namedImports} } from '${clientModule}';`
    );
  }

  /**
   * Add the `serializeShadowRoot` variable to the file if the hydrateModule is provided.
   */
  if (hydrateModule) {
    const initializer = serializeShadowRoot
      ? JSON.stringify(serializeShadowRoot)
      : '{ default: "declarative-shadow-dom" }';

    exports.push(`export const serializeShadowRoot: SerializeShadowRootOptions = ${initializer};`);
  }

  const importedEvents = new Set<string>();

  for (const component of components) {
    const tagName = component.tagName;
    const reactTagName = kebabToPascalCase(tagName);
    const componentElement = `${reactTagName}Element`;
    const componentCustomEvent = `${reactTagName}CustomEvent`;

    const namedImport = [
      `${reactTagName} as ${componentElement}`,
      !isSSRModule && `defineCustomElement as define${reactTagName}`,
    ]
      .filter(Boolean)
      .join(', ');

    imports.push(`import { ${namedImport} } from '${stencilPackageName}/${customElementsDir}/${tagName}.js';`);

    const events: ReactEvent[] = [];

    for (const event of component.events || []) {
      if (event.internal || !event.complexType) {
        continue;
      }

      const { references = {}, original } = event.complexType;
      /**
       * Import the referenced types from the component library.
       * Stencil will automatically re-export type definitions from the components,
       * if they are used in the component's property or event types.
       */
      for (const referenceKey of Object.keys(references)) {
        /**
         * Global type references should not have an explicit import.
         * The type should be available globally.
         */
        if (references[referenceKey].location !== 'global') {
          importedEvents.add(referenceKey);
        }
      }

      // Always type events using the Stencil per-component CustomEvent type.
      events.push({
        originalName: event.name,
        name: eventListenerName(event.name),
        type: `EventName<${componentCustomEvent}<${normalizeTypeString(original)}>>`,
      });
    }

    /**
     * Import the CustomEvent type for the web component from the Stencil package.
     *
     * For example:
     * ```
     * import type { ComponentCustomEvent } from 'my-component-library';
     * ```
     */
    if (events.length) {
      importedEvents.add(componentCustomEvent);
    }

    const componentEventNamesType = `${reactTagName}Events`;

    const requiredProps = component.properties.filter((p) => p.required && !p.internal).map((p) => `'${p.name}'`);
    const requiredGeneric = requiredProps.length > 0 ? `, ${requiredProps.join(' | ')}` : '';
    const eventType =
      events.length > 0
        ? `{\n  ${events.map(({ name, type }) => `${name}: ${type}`).join(',\n  ')}\n}`
        : 'NonNullable<unknown>';

    exports.push(`export type ${componentEventNamesType} = ${eventType};`);

    const clientComponentCall = [
      `/*@__PURE__*/ createComponent<${componentElement}, ${componentEventNamesType}, Components.${reactTagName}${requiredGeneric}>({`,
      `    tagName: '${tagName}',`,
      `    elementClass: ${componentElement},`,
      `    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.`,
      `    react: React,`,
      `    events: ${events.length ? `{\n      ${events.map((e) => `${e.name}: '${e.originalName}'`).join(',\n      ')}\n    }` : '{}'} as ${componentEventNamesType},`,
      `    defineCustomElement: define${reactTagName},`,
      transformTag && `    transformTag,`,
      `})`,
    ]
      .filter(Boolean)
      .join('\n');

    /**
     * Filter out properties that don't have an attribute.
     * These are properties with complex types and can't be serialized.
     */
    const serverProperties = component.properties
      .filter(({ attribute }) => Boolean(attribute))
      .map(({ name, attribute }) => `${name}: '${attribute}'`)
      .join(',\n      ');

    const serverComponentCall = [
      `/*@__PURE__*/ createComponent<${componentElement}, ${componentEventNamesType}, Components.${reactTagName}${requiredGeneric}>({`,
      `    tagName: '${tagName}',`,
      `    properties: {\n      ${serverProperties}\n    },`,
      `    hydrateModule: typeof window === 'undefined' ? (import('${hydrateModule}') as Promise<HydrateModule>) : undefined,`,
      `    clientModule: ${reactTagName}React as StencilReactComponent<${componentElement}, ${componentEventNamesType}, Components.${reactTagName}${requiredGeneric}>,`,
      `    serializeShadowRoot,`,
      transformTag && `    getTagTransformer,`,
      `})`,
    ]
      .filter(Boolean)
      .join('\n');

    const exportType = `StencilReactComponent<${componentElement}, ${componentEventNamesType}, Components.${reactTagName}${requiredGeneric}>`;
    exports.push(
      `export const ${reactTagName}: ${exportType} = ${hydrateModule ? serverComponentCall : clientComponentCall};`
    );
  }

  const hasEvents = Boolean(importedEvents.size);

  imports.push(
    hasEvents && `import type { ${Array.from(importedEvents).join(', ')} } from '${stencilPackageName}';`,
    `import type { StencilReactComponent${hasEvents ? ', EventName' : ''} } from '@stencil/react-output-target/runtime';`
  );

  return [
    /**
     * automatically attach the `use client` directive if we are not generating
     * server side rendering components.
     */
    `'use client';\n`,
    autogeneratedComment + '\n',
    `/* eslint-disable */\n`,
    imports.filter(Boolean).join('\n') + '\n',
    exports.filter(Boolean).join('\n\n') + '\n',
  ].join('\n');
};
