import { describe, it, expect } from 'vitest';
import { dedent } from 'ts-dedent';
import { Project } from 'ts-morph';

import { createComponentWrappers } from './create-component-wrappers.js';

describe('createComponentWrappers', () => {
  it('should generate a react component wrapper', async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFiles = await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          properties: [],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      project,
    });

    const sourceFile = sourceFiles[0];

    expect(sourceFile.getFullText()).toEqual(dedent`'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import React from 'react';
import { createComponent } from '@stencil/react-output-target/runtime';

import type { Components } from 'my-package/dist/custom-elements';
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from 'my-package/dist/custom-elements/my-component.js';
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

`);
  });

  it('should generate a react component wrapper with ES modules', async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFiles = await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          properties: [],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: true,
      project,
    });

    const componentsSourceFile = sourceFiles[0];
    expect(componentsSourceFile.getFullText()).toEqual(dedent`/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */
export { MyComponent } from "./my-component.js";

`);

    const sourceFile = sourceFiles[1];

    expect(sourceFile.getFullText()).toEqual(dedent`'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import React from 'react';
import { createComponent } from '@stencil/react-output-target/runtime';

import type { Components } from 'my-package/dist/custom-elements';
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from 'my-package/dist/custom-elements/my-component.js';
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

`);
  });

  it('should not generate component wrappers for internal components', async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFiles = await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          properties: [],
          internal: true,
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      project,
    });

    expect(sourceFiles).toEqual([]);
  });

  it('should filter out excludedComponents', async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFiles = await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      excludeComponents: ['my-component'],
      project,
    });

    expect(sourceFiles).toEqual([]);
  });

  // the import is generated correctly but its never used
  it('should generate event types from references', async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFiles = await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          properties: [],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              internal: false,
              complexType: {
                original: 'IMyComponent.Events.Detail.MyComponentClicked',
                resolved: '{ element: HTMLMyComponentElement; context: MyComponent; event: Event; }',
                references: {
                  IButton: {
                    location: 'import',
                    path: '../../types/my-component',
                    id: 'src/types/my-component.d.ts::IMyComponent',
                  },
                },
              },
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      project,
    });

    const sourceFile = sourceFiles[0];

    expect(sourceFile.getFullText()).toEqual(dedent`'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import React from 'react';
import { createComponent } from '@stencil/react-output-target/runtime';

import type { Components } from 'my-package/dist/custom-elements';
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from 'my-package/dist/custom-elements/my-component.js';
import { type IButton } from 'my-package';
import { type MyComponentCustomEvent } from 'my-package';
import type { StencilReactComponent, EventName } from '@stencil/react-output-target/runtime';

export type MyComponentEvents = { onMyEvent: EventName<MyComponentCustomEvent<IMyComponent.Events.Detail.MyComponentClicked>> };

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMyEvent: 'myEvent' } as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

    `);
  });

  it('creates next.js component wrappers', async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFiles = await createComponentWrappers({
      components: [
        {
          tagName: 'my-component',
          componentClassName: 'MyComponent',
          properties: [
            {
              name: 'hasMaxLength',
              attribute: 'max-length',
            },
            {
              name: 'links',
            },
          ],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      hydrateModule: 'my-package/hydrate',
      project,
    });

    expect(sourceFiles.length).toBe(2);
    const sourceFile = sourceFiles[1];

    const code = sourceFile.getFullText();
    expect(code)
      .toContain(`export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    properties: { hasMaxLength: 'max-length' },
    hydrateModule: typeof window === 'undefined' ? (import('my-package/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyComponent as StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>,
    serializeShadowRoot
});
`);
  });

  it('can exclude components for server side rendering', async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFiles = await createComponentWrappers({
      components: [
        {
          tagName: 'my-component-a',
          componentClassName: 'MyComponentA',
          properties: [
            {
              name: 'hasMaxLength',
              attribute: 'max-length',
            },
            {
              name: 'links',
            },
          ],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
        {
          tagName: 'my-component-b',
          componentClassName: 'MyComponentB',
          properties: [
            {
              name: 'hasMaxLength',
              attribute: 'max-length',
            },
            {
              name: 'links',
            },
          ],
          events: [
            {
              originalName: 'my-event',
              name: 'myEvent',
              type: 'CustomEvent',
            },
          ],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: false,
      hydrateModule: 'my-package/hydrate',
      excludeServerSideRenderingFor: ['my-component-a'],
      project,
    });

    const sourceFile = sourceFiles[1];

    const code = sourceFile.getFullText();
    expect(code).not.toContain('createComponent<MyComponentAElement, MyComponentAEvents, Components.MyComponentA>({');
    expect(code).toContain('createComponent<MyComponentBElement, MyComponentBEvents, Components.MyComponentB>({');
  });

  it('should generate a server barrel when esModules: true and hydrateModule are both set', async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFiles = await createComponentWrappers({
      components: [
        {
          tagName: 'my-component-a',
          componentClassName: 'MyComponentA',
          properties: [],
          events: [],
        } as any,
        {
          tagName: 'my-component-b',
          componentClassName: 'MyComponentB',
          properties: [],
          events: [],
        } as any,
      ],
      stencilPackageName: 'my-package',
      customElementsDir: 'dist/custom-elements',
      componentsTypesDir: 'dist/custom-elements',
      outDir: 'dist/my-output-path',
      esModules: true,
      hydrateModule: 'my-package/hydrate',
      excludeServerSideRenderingFor: ['my-component-a'],
      project,
    });

    /**
     * Find the generated barrels and per-component server files by file path
     * since the order of `sourceFiles` mixes the in-memory ts-morph results
     * (barrels) with the on-disk `createComponentFile` outputs.
     */
    const byPath = new Map(sourceFiles.map((f) => [f.getFilePath(), f]));

    const clientBarrel = [...byPath.keys()].find((p) => p.endsWith('/components.ts'));
    const serverBarrel = [...byPath.keys()].find((p) => p.endsWith('/components.server.ts'));
    const serverPerComponentA = [...byPath.keys()].find((p) => p.endsWith('/my-component-a.server.ts'));
    const serverPerComponentB = [...byPath.keys()].find((p) => p.endsWith('/my-component-b.server.ts'));

    expect(clientBarrel).toBeDefined();
    expect(serverBarrel).toBeDefined();

    /**
     * Per-component server file for the non-excluded component is still produced.
     * The excluded component's per-component server file ends up empty (filtered
     * to zero exports) — which matches the existing `createComponentFile` behavior
     * — so we don't assert on its absence here, only that the included one exists.
     */
    expect(serverPerComponentB).toBeDefined();

    const serverBarrelText = byPath.get(serverBarrel!)!.getFullText();
    expect(serverBarrelText).toContain(
      'import { type SerializeShadowRootOptions } from "@stencil/react-output-target/ssr";'
    );
    expect(serverBarrelText).toContain(
      'export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };'
    );
    expect(serverBarrelText).toContain('export { MyComponentB } from "./my-component-b.server.js";');
    expect(serverBarrelText).not.toContain('my-component-a.server.js');
    expect(serverBarrelText).not.toContain('MyComponentA');

    // Sanity check: the excluded per-component path is not silently used.
    expect(serverPerComponentA).toBeDefined(); // still emitted, but with no exports
  });
});
