import type { ComponentCompilerMeta } from '@stencil/core/internal';
import { kebabToPascalCase } from './utils/string-utils.js';
import type { RenderToStringOptions } from './runtime/ssr.js';

export const createEsModulesComponentsFile = ({
  components,
  componentSuffix = '',
  serializeShadowRoot,
}: {
  components: ComponentCompilerMeta[];
  componentSuffix?: string;
  serializeShadowRoot?: RenderToStringOptions['serializeShadowRoot'];
}) => {
  const disableEslint = `/* eslint-disable */`;
  const autogeneratedComment = `/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */\n\n`;
  const source = [autogeneratedComment + disableEslint];

  /**
   * Server barrel: emit a single shared `serializeShadowRoot` so consumers
   * don't need to import a per-component file just to get the constant.
   */
  if (componentSuffix) {
    const initializer = serializeShadowRoot
      ? JSON.stringify(serializeShadowRoot)
      : '{ default: "declarative-shadow-dom" }';

    source.push(
      `import type { SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';`,
      `export const serializeShadowRoot: SerializeShadowRootOptions = ${initializer};`
    );
  }

  for (const component of components) {
    const tagName = component.tagName;
    const reactTagName = kebabToPascalCase(tagName);
    const fileName = component.tagName;

    source.push(`export { ${reactTagName} } from './${fileName}${componentSuffix}.js';`);
  }

  return source.join('\n') + '\n';
};
