'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { getTagTransformer } from './tag-transformer.js';
import { createComponent, type SerializeShadowRootOptions, type HydrateModule } from '@stencil/react-output-target/ssr';
import type { Components } from 'component-library/components';
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from 'component-library-react';
import { MyButton as MyButtonElement } from 'component-library/components/my-button.js';
import { MyButtonScoped as MyButtonScopedElement } from 'component-library/components/my-button-scoped.js';
import { MyCheckbox as MyCheckboxElement } from 'component-library/components/my-checkbox.js';
import { MyComplexProps as MyComplexPropsElement } from 'component-library/components/my-complex-props.js';
import { MyComplexPropsScoped as MyComplexPropsScopedElement } from 'component-library/components/my-complex-props-scoped.js';
import { MyComponent as MyComponentElement } from 'component-library/components/my-component.js';
import { MyComponentDelegatesFocus as MyComponentDelegatesFocusElement } from 'component-library/components/my-component-delegates-focus.js';
import { MyComponentScoped as MyComponentScopedElement } from 'component-library/components/my-component-scoped.js';
import { MyCounter as MyCounterElement } from 'component-library/components/my-counter.js';
import { MyInput as MyInputElement } from 'component-library/components/my-input.js';
import { MyInputScoped as MyInputScopedElement } from 'component-library/components/my-input-scoped.js';
import { MyList as MyListElement } from 'component-library/components/my-list.js';
import { MyListItem as MyListItemElement } from 'component-library/components/my-list-item.js';
import { MyListItemScoped as MyListItemScopedElement } from 'component-library/components/my-list-item-scoped.js';
import { MyListScoped as MyListScopedElement } from 'component-library/components/my-list-scoped.js';
import { MyPopover as MyPopoverElement } from 'component-library/components/my-popover.js';
import { MyRadio as MyRadioElement } from 'component-library/components/my-radio.js';
import { MyRadioGroup as MyRadioGroupElement } from 'component-library/components/my-radio-group.js';
import { MyRange as MyRangeElement } from 'component-library/components/my-range.js';
import { MyToggle as MyToggleElement } from 'component-library/components/my-toggle.js';
import { MyToggleContent as MyToggleContentElement } from 'component-library/components/my-toggle-content.js';
import { MyTransformTest as MyTransformTestElement } from 'component-library/components/my-transform-test.js';
import type { MyButtonCustomEvent, MyButtonScopedCustomEvent, CheckboxChangeEventDetail, CheckboxChangeNestedEventDetail, MyCheckboxCustomEvent, MyComponentCustomEvent, IMyComponent, MyComponentScopedCustomEvent, MyCounterCustomEvent, InputChangeEventDetail, MyInputCustomEvent, MyInputScopedCustomEvent, OverlayEventDetail, MyPopoverCustomEvent, MyRadioCustomEvent, RadioGroupChangeEventDetail, MyRadioGroupCustomEvent, RangeChangeEventDetail, MyRangeCustomEvent } from 'component-library';
import type { StencilReactComponent, EventName } from '@stencil/react-output-target/runtime';

export const serializeShadowRoot: SerializeShadowRootOptions = {"scoped":["my-counter","my-button","my-component","my-radio"],"default":"declarative-shadow-dom"};

export type MyButtonEvents = {
  onMyFocus: EventName<MyButtonCustomEvent<void>>,
  onMyBlur: EventName<MyButtonCustomEvent<void>>
};

export const MyButton: StencilReactComponent<MyButtonElement, MyButtonEvents, Components.MyButton> = /*@__PURE__*/ createComponent<MyButtonElement, MyButtonEvents, Components.MyButton>({
    tagName: 'my-button',
    properties: {
      color: 'color',
      buttonType: 'button-type',
      disabled: 'disabled',
      expand: 'expand',
      fill: 'fill',
      download: 'download',
      href: 'href',
      rel: 'rel',
      shape: 'shape',
      size: 'size',
      strong: 'strong',
      target: 'target',
      type: 'type'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyButton as StencilReactComponent<MyButtonElement, MyButtonEvents, Components.MyButton>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyButtonScopedEvents = {
  onMyFocus: EventName<MyButtonScopedCustomEvent<void>>,
  onMyBlur: EventName<MyButtonScopedCustomEvent<void>>
};

export const MyButtonScoped: StencilReactComponent<MyButtonScopedElement, MyButtonScopedEvents, Components.MyButtonScoped> = /*@__PURE__*/ createComponent<MyButtonScopedElement, MyButtonScopedEvents, Components.MyButtonScoped>({
    tagName: 'my-button-scoped',
    properties: {
      color: 'color',
      buttonType: 'button-type',
      disabled: 'disabled',
      expand: 'expand',
      fill: 'fill',
      download: 'download',
      href: 'href',
      rel: 'rel',
      shape: 'shape',
      size: 'size',
      strong: 'strong',
      target: 'target',
      type: 'type'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyButtonScoped as StencilReactComponent<MyButtonScopedElement, MyButtonScopedEvents, Components.MyButtonScoped>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyCheckboxEvents = {
  onIonChange: EventName<MyCheckboxCustomEvent<CheckboxChangeEventDetail>>,
  onIonChangeNested: EventName<MyCheckboxCustomEvent<CheckboxChangeNestedEventDetail>>,
  onIonFocus: EventName<MyCheckboxCustomEvent<void>>,
  onIonBlur: EventName<MyCheckboxCustomEvent<void>>
};

export const MyCheckbox: StencilReactComponent<MyCheckboxElement, MyCheckboxEvents, Components.MyCheckbox> = /*@__PURE__*/ createComponent<MyCheckboxElement, MyCheckboxEvents, Components.MyCheckbox>({
    tagName: 'my-checkbox',
    properties: {
      color: 'color',
      name: 'name',
      checked: 'checked',
      indeterminate: 'indeterminate',
      disabled: 'disabled',
      value: 'value',
      labelPlacement: 'label-placement',
      justify: 'justify',
      alignment: 'alignment'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyCheckbox as StencilReactComponent<MyCheckboxElement, MyCheckboxEvents, Components.MyCheckbox>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyComplexPropsEvents = NonNullable<unknown>;

export const MyComplexProps: StencilReactComponent<MyComplexPropsElement, MyComplexPropsEvents, Components.MyComplexProps> = /*@__PURE__*/ createComponent<MyComplexPropsElement, MyComplexPropsEvents, Components.MyComplexProps>({
    tagName: 'my-complex-props',
    properties: {
      grault: 'grault'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyComplexProps as StencilReactComponent<MyComplexPropsElement, MyComplexPropsEvents, Components.MyComplexProps>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyComplexPropsScopedEvents = NonNullable<unknown>;

export const MyComplexPropsScoped: StencilReactComponent<MyComplexPropsScopedElement, MyComplexPropsScopedEvents, Components.MyComplexPropsScoped> = /*@__PURE__*/ createComponent<MyComplexPropsScopedElement, MyComplexPropsScopedEvents, Components.MyComplexPropsScoped>({
    tagName: 'my-complex-props-scoped',
    properties: {
      grault: 'grault'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyComplexPropsScoped as StencilReactComponent<MyComplexPropsScopedElement, MyComplexPropsScopedEvents, Components.MyComplexPropsScoped>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyComponentEvents = {
  onMyCustomEvent: EventName<MyComponentCustomEvent<void>>
};

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    properties: {
      first: 'first',
      middleName: 'middle-name',
      last: 'last'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyComponent as StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyComponentDelegatesFocusEvents = NonNullable<unknown>;

export const MyComponentDelegatesFocus: StencilReactComponent<MyComponentDelegatesFocusElement, MyComponentDelegatesFocusEvents, Components.MyComponentDelegatesFocus> = /*@__PURE__*/ createComponent<MyComponentDelegatesFocusElement, MyComponentDelegatesFocusEvents, Components.MyComponentDelegatesFocus>({
    tagName: 'my-component-delegates-focus',
    properties: {
      
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyComponentDelegatesFocus as StencilReactComponent<MyComponentDelegatesFocusElement, MyComponentDelegatesFocusEvents, Components.MyComponentDelegatesFocus>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyComponentScopedEvents = {
  onMyCustomEvent: EventName<MyComponentScopedCustomEvent<IMyComponent.someVar>>
};

export const MyComponentScoped: StencilReactComponent<MyComponentScopedElement, MyComponentScopedEvents, Components.MyComponentScoped> = /*@__PURE__*/ createComponent<MyComponentScopedElement, MyComponentScopedEvents, Components.MyComponentScoped>({
    tagName: 'my-component-scoped',
    properties: {
      first: 'first',
      middleName: 'middle-name',
      last: 'last'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyComponentScoped as StencilReactComponent<MyComponentScopedElement, MyComponentScopedEvents, Components.MyComponentScoped>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyCounterEvents = {
  onCount: EventName<MyCounterCustomEvent<number>>
};

export const MyCounter: StencilReactComponent<MyCounterElement, MyCounterEvents, Components.MyCounter> = /*@__PURE__*/ createComponent<MyCounterElement, MyCounterEvents, Components.MyCounter>({
    tagName: 'my-counter',
    properties: {
      startValue: 'start-value'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyCounter as StencilReactComponent<MyCounterElement, MyCounterEvents, Components.MyCounter>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyInputEvents = {
  onMyInput: EventName<MyInputCustomEvent<KeyboardEvent>>,
  onMyChange: EventName<MyInputCustomEvent<InputChangeEventDetail>>,
  onMyBlur: EventName<MyInputCustomEvent<void>>,
  onMyFocus: EventName<MyInputCustomEvent<void>>
};

export const MyInput: StencilReactComponent<MyInputElement, MyInputEvents, Components.MyInput> = /*@__PURE__*/ createComponent<MyInputElement, MyInputEvents, Components.MyInput>({
    tagName: 'my-input',
    properties: {
      color: 'color',
      accept: 'accept',
      autocapitalize: 'autocapitalize',
      autocomplete: 'autocomplete',
      autocorrect: 'autocorrect',
      autofocus: 'autofocus',
      clearInput: 'clear-input',
      clearOnEdit: 'clear-on-edit',
      disabled: 'disabled',
      enterkeyhint: 'enterkeyhint',
      inputmode: 'inputmode',
      max: 'max',
      maxlength: 'maxlength',
      min: 'min',
      minlength: 'minlength',
      multiple: 'multiple',
      name: 'name',
      pattern: 'pattern',
      placeholder: 'placeholder',
      readonly: 'readonly',
      required: 'required',
      spellcheck: 'spellcheck',
      step: 'step',
      size: 'size',
      type: 'type',
      value: 'value'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyInput as StencilReactComponent<MyInputElement, MyInputEvents, Components.MyInput>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyInputScopedEvents = {
  onMyInput: EventName<MyInputScopedCustomEvent<KeyboardEvent>>,
  onMyChange: EventName<MyInputScopedCustomEvent<InputChangeEventDetail>>,
  onMyBlur: EventName<MyInputScopedCustomEvent<void>>,
  onMyFocus: EventName<MyInputScopedCustomEvent<void>>
};

export const MyInputScoped: StencilReactComponent<MyInputScopedElement, MyInputScopedEvents, Components.MyInputScoped> = /*@__PURE__*/ createComponent<MyInputScopedElement, MyInputScopedEvents, Components.MyInputScoped>({
    tagName: 'my-input-scoped',
    properties: {
      color: 'color',
      accept: 'accept',
      autocapitalize: 'autocapitalize',
      autocomplete: 'autocomplete',
      autocorrect: 'autocorrect',
      autofocus: 'autofocus',
      clearInput: 'clear-input',
      clearOnEdit: 'clear-on-edit',
      disabled: 'disabled',
      enterkeyhint: 'enterkeyhint',
      inputmode: 'inputmode',
      max: 'max',
      maxlength: 'maxlength',
      min: 'min',
      minlength: 'minlength',
      multiple: 'multiple',
      name: 'name',
      pattern: 'pattern',
      placeholder: 'placeholder',
      readonly: 'readonly',
      required: 'required',
      spellcheck: 'spellcheck',
      step: 'step',
      size: 'size',
      type: 'type',
      value: 'value'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyInputScoped as StencilReactComponent<MyInputScopedElement, MyInputScopedEvents, Components.MyInputScoped>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyListEvents = NonNullable<unknown>;

export const MyList: StencilReactComponent<MyListElement, MyListEvents, Components.MyList> = /*@__PURE__*/ createComponent<MyListElement, MyListEvents, Components.MyList>({
    tagName: 'my-list',
    properties: {
      
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyList as StencilReactComponent<MyListElement, MyListEvents, Components.MyList>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyListItemEvents = NonNullable<unknown>;

export const MyListItem: StencilReactComponent<MyListItemElement, MyListItemEvents, Components.MyListItem> = /*@__PURE__*/ createComponent<MyListItemElement, MyListItemEvents, Components.MyListItem>({
    tagName: 'my-list-item',
    properties: {
      
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyListItem as StencilReactComponent<MyListItemElement, MyListItemEvents, Components.MyListItem>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyListItemScopedEvents = NonNullable<unknown>;

export const MyListItemScoped: StencilReactComponent<MyListItemScopedElement, MyListItemScopedEvents, Components.MyListItemScoped> = /*@__PURE__*/ createComponent<MyListItemScopedElement, MyListItemScopedEvents, Components.MyListItemScoped>({
    tagName: 'my-list-item-scoped',
    properties: {
      
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyListItemScoped as StencilReactComponent<MyListItemScopedElement, MyListItemScopedEvents, Components.MyListItemScoped>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyListScopedEvents = NonNullable<unknown>;

export const MyListScoped: StencilReactComponent<MyListScopedElement, MyListScopedEvents, Components.MyListScoped> = /*@__PURE__*/ createComponent<MyListScopedElement, MyListScopedEvents, Components.MyListScoped>({
    tagName: 'my-list-scoped',
    properties: {
      
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyListScoped as StencilReactComponent<MyListScopedElement, MyListScopedEvents, Components.MyListScoped>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyPopoverEvents = {
  onMyPopoverDidPresent: EventName<MyPopoverCustomEvent<void>>,
  onMyPopoverWillPresent: EventName<MyPopoverCustomEvent<void>>,
  onMyPopoverWillDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>,
  onMyPopoverDidDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>
};

export const MyPopover: StencilReactComponent<MyPopoverElement, MyPopoverEvents, Components.MyPopover, 'component'> = /*@__PURE__*/ createComponent<MyPopoverElement, MyPopoverEvents, Components.MyPopover, 'component'>({
    tagName: 'my-popover',
    properties: {
      component: 'component',
      keyboardClose: 'keyboard-close',
      cssClass: 'css-class',
      backdropDismiss: 'backdrop-dismiss',
      event: 'event',
      showBackdrop: 'show-backdrop',
      translucent: 'translucent',
      animated: 'animated'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyPopover as StencilReactComponent<MyPopoverElement, MyPopoverEvents, Components.MyPopover, 'component'>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyRadioEvents = {
  onIonFocus: EventName<MyRadioCustomEvent<void>>,
  onIonBlur: EventName<MyRadioCustomEvent<void>>
};

export const MyRadio: StencilReactComponent<MyRadioElement, MyRadioEvents, Components.MyRadio> = /*@__PURE__*/ createComponent<MyRadioElement, MyRadioEvents, Components.MyRadio>({
    tagName: 'my-radio',
    properties: {
      color: 'color',
      name: 'name',
      disabled: 'disabled',
      value: 'value',
      labelPlacement: 'label-placement',
      justify: 'justify',
      alignment: 'alignment'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyRadio as StencilReactComponent<MyRadioElement, MyRadioEvents, Components.MyRadio>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyRadioGroupEvents = {
  onMyChange: EventName<MyRadioGroupCustomEvent<RadioGroupChangeEventDetail>>
};

export const MyRadioGroup: StencilReactComponent<MyRadioGroupElement, MyRadioGroupEvents, Components.MyRadioGroup> = /*@__PURE__*/ createComponent<MyRadioGroupElement, MyRadioGroupEvents, Components.MyRadioGroup>({
    tagName: 'my-radio-group',
    properties: {
      allowEmptySelection: 'allow-empty-selection',
      compareWith: 'compare-with',
      name: 'name',
      value: 'value'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyRadioGroup as StencilReactComponent<MyRadioGroupElement, MyRadioGroupEvents, Components.MyRadioGroup>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyRangeEvents = {
  onMyChange: EventName<MyRangeCustomEvent<RangeChangeEventDetail>>,
  onMyFocus: EventName<MyRangeCustomEvent<void>>,
  onMyBlur: EventName<MyRangeCustomEvent<void>>
};

export const MyRange: StencilReactComponent<MyRangeElement, MyRangeEvents, Components.MyRange> = /*@__PURE__*/ createComponent<MyRangeElement, MyRangeEvents, Components.MyRange>({
    tagName: 'my-range',
    properties: {
      color: 'color',
      debounce: 'debounce',
      name: 'name',
      dualKnobs: 'dual-knobs',
      min: 'min',
      max: 'max',
      pin: 'pin',
      snaps: 'snaps',
      step: 'step',
      ticks: 'ticks',
      disabled: 'disabled',
      value: 'value'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyRange as StencilReactComponent<MyRangeElement, MyRangeEvents, Components.MyRange>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyToggleEvents = NonNullable<unknown>;

export const MyToggle: StencilReactComponent<MyToggleElement, MyToggleEvents, Components.MyToggle> = /*@__PURE__*/ createComponent<MyToggleElement, MyToggleEvents, Components.MyToggle>({
    tagName: 'my-toggle',
    properties: {
      
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyToggle as StencilReactComponent<MyToggleElement, MyToggleEvents, Components.MyToggle>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyToggleContentEvents = NonNullable<unknown>;

export const MyToggleContent: StencilReactComponent<MyToggleContentElement, MyToggleContentEvents, Components.MyToggleContent> = /*@__PURE__*/ createComponent<MyToggleContentElement, MyToggleContentEvents, Components.MyToggleContent>({
    tagName: 'my-toggle-content',
    properties: {
      visible: 'visible'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyToggleContent as StencilReactComponent<MyToggleContentElement, MyToggleContentEvents, Components.MyToggleContent>,
    serializeShadowRoot,
    getTagTransformer,
});

export type MyTransformTestEvents = NonNullable<unknown>;

export const MyTransformTest: StencilReactComponent<MyTransformTestElement, MyTransformTestEvents, Components.MyTransformTest> = /*@__PURE__*/ createComponent<MyTransformTestElement, MyTransformTestEvents, Components.MyTransformTest>({
    tagName: 'my-transform-test',
    properties: {
      message: 'message'
    },
    hydrateModule: typeof window === 'undefined' ? (import('component-library/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.MyTransformTest as StencilReactComponent<MyTransformTestElement, MyTransformTestEvents, Components.MyTransformTest>,
    serializeShadowRoot,
    getTagTransformer,
});
