'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import React from 'react';
import { createComponent } from '@stencil/react-output-target/runtime';
import { transformTag } from './tag-transformer.js';

import type { Components } from 'component-library/components';
import { MyButton as MyButtonElement, defineCustomElement as defineMyButton } from 'component-library/components/my-button.js';
import { type MyButtonCustomEvent } from 'component-library';
import { MyButtonScoped as MyButtonScopedElement, defineCustomElement as defineMyButtonScoped } from 'component-library/components/my-button-scoped.js';
import { type MyButtonScopedCustomEvent } from 'component-library';
import { MyCheckbox as MyCheckboxElement, defineCustomElement as defineMyCheckbox } from 'component-library/components/my-checkbox.js';
import { type CheckboxChangeEventDetail } from 'component-library';
import { type MyCheckboxCustomEvent } from 'component-library';
import { type CheckboxChangeNestedEventDetail } from 'component-library';
import { MyComplexProps as MyComplexPropsElement, defineCustomElement as defineMyComplexProps } from 'component-library/components/my-complex-props.js';
import { MyComplexPropsScoped as MyComplexPropsScopedElement, defineCustomElement as defineMyComplexPropsScoped } from 'component-library/components/my-complex-props-scoped.js';
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from 'component-library/components/my-component.js';
import { type MyComponentCustomEvent } from 'component-library';
import { MyComponentDelegatesFocus as MyComponentDelegatesFocusElement, defineCustomElement as defineMyComponentDelegatesFocus } from 'component-library/components/my-component-delegates-focus.js';
import { MyComponentScoped as MyComponentScopedElement, defineCustomElement as defineMyComponentScoped } from 'component-library/components/my-component-scoped.js';
import { type IMyComponent } from 'component-library';
import { type MyComponentScopedCustomEvent } from 'component-library';
import { MyCounter as MyCounterElement, defineCustomElement as defineMyCounter } from 'component-library/components/my-counter.js';
import { type MyCounterCustomEvent } from 'component-library';
import { MyInput as MyInputElement, defineCustomElement as defineMyInput } from 'component-library/components/my-input.js';
import { type MyInputCustomEvent } from 'component-library';
import { type InputChangeEventDetail } from 'component-library';
import { MyInputScoped as MyInputScopedElement, defineCustomElement as defineMyInputScoped } from 'component-library/components/my-input-scoped.js';
import { type MyInputScopedCustomEvent } from 'component-library';
import { MyList as MyListElement, defineCustomElement as defineMyList } from 'component-library/components/my-list.js';
import { MyListItem as MyListItemElement, defineCustomElement as defineMyListItem } from 'component-library/components/my-list-item.js';
import { MyListItemScoped as MyListItemScopedElement, defineCustomElement as defineMyListItemScoped } from 'component-library/components/my-list-item-scoped.js';
import { MyListScoped as MyListScopedElement, defineCustomElement as defineMyListScoped } from 'component-library/components/my-list-scoped.js';
import { MyPopover as MyPopoverElement, defineCustomElement as defineMyPopover } from 'component-library/components/my-popover.js';
import { type MyPopoverCustomEvent } from 'component-library';
import { type OverlayEventDetail } from 'component-library';
import { MyRadio as MyRadioElement, defineCustomElement as defineMyRadio } from 'component-library/components/my-radio.js';
import { type MyRadioCustomEvent } from 'component-library';
import { MyRadioGroup as MyRadioGroupElement, defineCustomElement as defineMyRadioGroup } from 'component-library/components/my-radio-group.js';
import { type RadioGroupChangeEventDetail } from 'component-library';
import { type MyRadioGroupCustomEvent } from 'component-library';
import { MyRange as MyRangeElement, defineCustomElement as defineMyRange } from 'component-library/components/my-range.js';
import { type RangeChangeEventDetail } from 'component-library';
import { type MyRangeCustomEvent } from 'component-library';
import { MyToggle as MyToggleElement, defineCustomElement as defineMyToggle } from 'component-library/components/my-toggle.js';
import { MyToggleContent as MyToggleContentElement, defineCustomElement as defineMyToggleContent } from 'component-library/components/my-toggle-content.js';
import { MyTransformTest as MyTransformTestElement, defineCustomElement as defineMyTransformTest } from 'component-library/components/my-transform-test.js';
import type { StencilReactComponent, EventName } from '@stencil/react-output-target/runtime';

export type MyButtonEvents = {
    onMyFocus: EventName<MyButtonCustomEvent<void>>,
    onMyBlur: EventName<MyButtonCustomEvent<void>>
};

export const MyButton: StencilReactComponent<MyButtonElement, MyButtonEvents, Components.MyButton> = /*@__PURE__*/ createComponent<MyButtonElement, MyButtonEvents, Components.MyButton>({
    tagName: 'my-button',
    elementClass: MyButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMyFocus: 'myFocus',
        onMyBlur: 'myBlur'
    } as MyButtonEvents,
    defineCustomElement: defineMyButton,
    transformTag
});

export type MyButtonScopedEvents = {
    onMyFocus: EventName<MyButtonScopedCustomEvent<void>>,
    onMyBlur: EventName<MyButtonScopedCustomEvent<void>>
};

export const MyButtonScoped: StencilReactComponent<MyButtonScopedElement, MyButtonScopedEvents, Components.MyButtonScoped> = /*@__PURE__*/ createComponent<MyButtonScopedElement, MyButtonScopedEvents, Components.MyButtonScoped>({
    tagName: 'my-button-scoped',
    elementClass: MyButtonScopedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMyFocus: 'myFocus',
        onMyBlur: 'myBlur'
    } as MyButtonScopedEvents,
    defineCustomElement: defineMyButtonScoped,
    transformTag
});

export type MyCheckboxEvents = {
    onIonChange: EventName<MyCheckboxCustomEvent<CheckboxChangeEventDetail>>,
    onIonChangeNested: EventName<MyCheckboxCustomEvent<CheckboxChangeNestedEventDetail>>,
    onIonFocus: EventName<MyCheckboxCustomEvent<void>>,
    onIonBlur: EventName<MyCheckboxCustomEvent<void>>
};

export const MyCheckbox: StencilReactComponent<MyCheckboxElement, MyCheckboxEvents, Components.MyCheckbox> = /*@__PURE__*/ createComponent<MyCheckboxElement, MyCheckboxEvents, Components.MyCheckbox>({
    tagName: 'my-checkbox',
    elementClass: MyCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onIonChange: 'ionChange',
        onIonChangeNested: 'ionChangeNested',
        onIonFocus: 'ionFocus',
        onIonBlur: 'ionBlur'
    } as MyCheckboxEvents,
    defineCustomElement: defineMyCheckbox,
    transformTag
});

export type MyComplexPropsEvents = NonNullable<unknown>;

export const MyComplexProps: StencilReactComponent<MyComplexPropsElement, MyComplexPropsEvents, Components.MyComplexProps> = /*@__PURE__*/ createComponent<MyComplexPropsElement, MyComplexPropsEvents, Components.MyComplexProps>({
    tagName: 'my-complex-props',
    elementClass: MyComplexPropsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComplexPropsEvents,
    defineCustomElement: defineMyComplexProps,
    transformTag
});

export type MyComplexPropsScopedEvents = NonNullable<unknown>;

export const MyComplexPropsScoped: StencilReactComponent<MyComplexPropsScopedElement, MyComplexPropsScopedEvents, Components.MyComplexPropsScoped> = /*@__PURE__*/ createComponent<MyComplexPropsScopedElement, MyComplexPropsScopedEvents, Components.MyComplexPropsScoped>({
    tagName: 'my-complex-props-scoped',
    elementClass: MyComplexPropsScopedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComplexPropsScopedEvents,
    defineCustomElement: defineMyComplexPropsScoped,
    transformTag
});

export type MyComponentEvents = { onMyCustomEvent: EventName<MyComponentCustomEvent<void>> };

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMyCustomEvent: 'myCustomEvent' } as MyComponentEvents,
    defineCustomElement: defineMyComponent,
    transformTag
});

export type MyComponentDelegatesFocusEvents = NonNullable<unknown>;

export const MyComponentDelegatesFocus: StencilReactComponent<MyComponentDelegatesFocusElement, MyComponentDelegatesFocusEvents, Components.MyComponentDelegatesFocus> = /*@__PURE__*/ createComponent<MyComponentDelegatesFocusElement, MyComponentDelegatesFocusEvents, Components.MyComponentDelegatesFocus>({
    tagName: 'my-component-delegates-focus',
    elementClass: MyComponentDelegatesFocusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentDelegatesFocusEvents,
    defineCustomElement: defineMyComponentDelegatesFocus,
    transformTag
});

export type MyComponentScopedEvents = { onMyCustomEvent: EventName<MyComponentScopedCustomEvent<IMyComponent.someVar>> };

export const MyComponentScoped: StencilReactComponent<MyComponentScopedElement, MyComponentScopedEvents, Components.MyComponentScoped> = /*@__PURE__*/ createComponent<MyComponentScopedElement, MyComponentScopedEvents, Components.MyComponentScoped>({
    tagName: 'my-component-scoped',
    elementClass: MyComponentScopedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMyCustomEvent: 'myCustomEvent' } as MyComponentScopedEvents,
    defineCustomElement: defineMyComponentScoped,
    transformTag
});

export type MyCounterEvents = { onCount: EventName<MyCounterCustomEvent<number>> };

export const MyCounter: StencilReactComponent<MyCounterElement, MyCounterEvents, Components.MyCounter> = /*@__PURE__*/ createComponent<MyCounterElement, MyCounterEvents, Components.MyCounter>({
    tagName: 'my-counter',
    elementClass: MyCounterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCount: 'count' } as MyCounterEvents,
    defineCustomElement: defineMyCounter,
    transformTag
});

export type MyInputEvents = {
    onMyInput: EventName<MyInputCustomEvent<KeyboardEvent>>,
    onMyChange: EventName<MyInputCustomEvent<InputChangeEventDetail>>,
    onMyBlur: EventName<MyInputCustomEvent<void>>,
    onMyFocus: EventName<MyInputCustomEvent<void>>
};

export const MyInput: StencilReactComponent<MyInputElement, MyInputEvents, Components.MyInput> = /*@__PURE__*/ createComponent<MyInputElement, MyInputEvents, Components.MyInput>({
    tagName: 'my-input',
    elementClass: MyInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMyInput: 'myInput',
        onMyChange: 'myChange',
        onMyBlur: 'myBlur',
        onMyFocus: 'myFocus'
    } as MyInputEvents,
    defineCustomElement: defineMyInput,
    transformTag
});

export type MyInputScopedEvents = {
    onMyInput: EventName<MyInputScopedCustomEvent<KeyboardEvent>>,
    onMyChange: EventName<MyInputScopedCustomEvent<InputChangeEventDetail>>,
    onMyBlur: EventName<MyInputScopedCustomEvent<void>>,
    onMyFocus: EventName<MyInputScopedCustomEvent<void>>
};

export const MyInputScoped: StencilReactComponent<MyInputScopedElement, MyInputScopedEvents, Components.MyInputScoped> = /*@__PURE__*/ createComponent<MyInputScopedElement, MyInputScopedEvents, Components.MyInputScoped>({
    tagName: 'my-input-scoped',
    elementClass: MyInputScopedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMyInput: 'myInput',
        onMyChange: 'myChange',
        onMyBlur: 'myBlur',
        onMyFocus: 'myFocus'
    } as MyInputScopedEvents,
    defineCustomElement: defineMyInputScoped,
    transformTag
});

export type MyListEvents = NonNullable<unknown>;

export const MyList: StencilReactComponent<MyListElement, MyListEvents, Components.MyList> = /*@__PURE__*/ createComponent<MyListElement, MyListEvents, Components.MyList>({
    tagName: 'my-list',
    elementClass: MyListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyListEvents,
    defineCustomElement: defineMyList,
    transformTag
});

export type MyListItemEvents = NonNullable<unknown>;

export const MyListItem: StencilReactComponent<MyListItemElement, MyListItemEvents, Components.MyListItem> = /*@__PURE__*/ createComponent<MyListItemElement, MyListItemEvents, Components.MyListItem>({
    tagName: 'my-list-item',
    elementClass: MyListItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyListItemEvents,
    defineCustomElement: defineMyListItem,
    transformTag
});

export type MyListItemScopedEvents = NonNullable<unknown>;

export const MyListItemScoped: StencilReactComponent<MyListItemScopedElement, MyListItemScopedEvents, Components.MyListItemScoped> = /*@__PURE__*/ createComponent<MyListItemScopedElement, MyListItemScopedEvents, Components.MyListItemScoped>({
    tagName: 'my-list-item-scoped',
    elementClass: MyListItemScopedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyListItemScopedEvents,
    defineCustomElement: defineMyListItemScoped,
    transformTag
});

export type MyListScopedEvents = NonNullable<unknown>;

export const MyListScoped: StencilReactComponent<MyListScopedElement, MyListScopedEvents, Components.MyListScoped> = /*@__PURE__*/ createComponent<MyListScopedElement, MyListScopedEvents, Components.MyListScoped>({
    tagName: 'my-list-scoped',
    elementClass: MyListScopedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyListScopedEvents,
    defineCustomElement: defineMyListScoped,
    transformTag
});

export type MyPopoverEvents = {
    onMyPopoverDidPresent: EventName<MyPopoverCustomEvent<void>>,
    onMyPopoverWillPresent: EventName<MyPopoverCustomEvent<void>>,
    onMyPopoverWillDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>,
    onMyPopoverDidDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>
};

export const MyPopover: StencilReactComponent<MyPopoverElement, MyPopoverEvents, Components.MyPopover, 'component'> = /*@__PURE__*/ createComponent<MyPopoverElement, MyPopoverEvents, Components.MyPopover, 'component'>({
    tagName: 'my-popover',
    elementClass: MyPopoverElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMyPopoverDidPresent: 'myPopoverDidPresent',
        onMyPopoverWillPresent: 'myPopoverWillPresent',
        onMyPopoverWillDismiss: 'myPopoverWillDismiss',
        onMyPopoverDidDismiss: 'myPopoverDidDismiss'
    } as MyPopoverEvents,
    defineCustomElement: defineMyPopover,
    transformTag
});

export type MyRadioEvents = {
    onIonFocus: EventName<MyRadioCustomEvent<void>>,
    onIonBlur: EventName<MyRadioCustomEvent<void>>
};

export const MyRadio: StencilReactComponent<MyRadioElement, MyRadioEvents, Components.MyRadio> = /*@__PURE__*/ createComponent<MyRadioElement, MyRadioEvents, Components.MyRadio>({
    tagName: 'my-radio',
    elementClass: MyRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onIonFocus: 'ionFocus',
        onIonBlur: 'ionBlur'
    } as MyRadioEvents,
    defineCustomElement: defineMyRadio,
    transformTag
});

export type MyRadioGroupEvents = { onMyChange: EventName<MyRadioGroupCustomEvent<RadioGroupChangeEventDetail>> };

export const MyRadioGroup: StencilReactComponent<MyRadioGroupElement, MyRadioGroupEvents, Components.MyRadioGroup> = /*@__PURE__*/ createComponent<MyRadioGroupElement, MyRadioGroupEvents, Components.MyRadioGroup>({
    tagName: 'my-radio-group',
    elementClass: MyRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMyChange: 'myChange' } as MyRadioGroupEvents,
    defineCustomElement: defineMyRadioGroup,
    transformTag
});

export type MyRangeEvents = {
    onMyChange: EventName<MyRangeCustomEvent<RangeChangeEventDetail>>,
    onMyFocus: EventName<MyRangeCustomEvent<void>>,
    onMyBlur: EventName<MyRangeCustomEvent<void>>
};

export const MyRange: StencilReactComponent<MyRangeElement, MyRangeEvents, Components.MyRange> = /*@__PURE__*/ createComponent<MyRangeElement, MyRangeEvents, Components.MyRange>({
    tagName: 'my-range',
    elementClass: MyRangeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMyChange: 'myChange',
        onMyFocus: 'myFocus',
        onMyBlur: 'myBlur'
    } as MyRangeEvents,
    defineCustomElement: defineMyRange,
    transformTag
});

export type MyToggleEvents = NonNullable<unknown>;

export const MyToggle: StencilReactComponent<MyToggleElement, MyToggleEvents, Components.MyToggle> = /*@__PURE__*/ createComponent<MyToggleElement, MyToggleEvents, Components.MyToggle>({
    tagName: 'my-toggle',
    elementClass: MyToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyToggleEvents,
    defineCustomElement: defineMyToggle,
    transformTag
});

export type MyToggleContentEvents = NonNullable<unknown>;

export const MyToggleContent: StencilReactComponent<MyToggleContentElement, MyToggleContentEvents, Components.MyToggleContent> = /*@__PURE__*/ createComponent<MyToggleContentElement, MyToggleContentEvents, Components.MyToggleContent>({
    tagName: 'my-toggle-content',
    elementClass: MyToggleContentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyToggleContentEvents,
    defineCustomElement: defineMyToggleContent,
    transformTag
});

export type MyTransformTestEvents = NonNullable<unknown>;

export const MyTransformTest: StencilReactComponent<MyTransformTestElement, MyTransformTestEvents, Components.MyTransformTest> = /*@__PURE__*/ createComponent<MyTransformTestElement, MyTransformTestEvents, Components.MyTransformTest>({
    tagName: 'my-transform-test',
    elementClass: MyTransformTestElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyTransformTestEvents,
    defineCustomElement: defineMyTransformTest,
    transformTag
});
